import { makeStyles, tokens } from "@fluentui/react-components";

export const useTeamsDialerStyles = makeStyles({
  overlay: {
    position: "fixed",
    top: 0,
    left: 0,
    width: "100vw",
    height: "100vh",
    zIndex: 9999,
    pointerEvents: "none",
  },
  popup: {
    position: "absolute",
    top: "80px",
    right: "40px",
    width: "340px",
    borderRadius: "8px",
    overflow: "hidden",
    boxShadow: "0 8px 32px rgba(0, 0, 0, 0.4)",
    pointerEvents: "auto",
    display: "flex",
    flexDirection: "column",
    fontFamily: tokens.fontFamilyBase,
  },
  // Title bar
  titleBar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#fff",
    paddingTop: "8px",
    paddingBottom: "8px",
    paddingLeft: "12px",
    paddingRight: "8px",
    borderBottom: "1px solid #e0e0e0",
  },
  titleLeft: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  teamsIcon: {
    width: "20px",
    height: "20px",
  },
  titleText: {
    fontSize: "14px",
    fontWeight: 600,
    color: "#242424",
  },
  titleActions: {
    display: "flex",
    alignItems: "center",
    gap: "2px",
  },
  // Control bar (timer + buttons)
  controlBar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#292929",
    paddingTop: "6px",
    paddingBottom: "6px",
    paddingLeft: "12px",
    paddingRight: "8px",
  },
  timerSection: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  recordDot: {
    width: "10px",
    height: "10px",
    borderRadius: "50%",
    backgroundColor: "#d13438",
    flexShrink: 0,
  },
  timerText: {
    fontSize: "13px",
    color: "#fff",
    fontVariantNumeric: "tabular-nums",
  },
  controlButtons: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
  },
  controlBtn: {
    color: "#fff",
    backgroundColor: "transparent",
    borderRadius: "4px",
    width: "32px",
    height: "32px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    border: "none",
    cursor: "pointer",
    ":hover": {
      backgroundColor: "rgba(255,255,255,0.1)",
    },
  },
  controlBtnActive: {
    backgroundColor: "rgba(255,255,255,0.15)",
  },
  hangUpBtn: {
    backgroundColor: "#d13438",
    color: "#fff",
    borderRadius: "4px",
    width: "32px",
    height: "32px",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    border: "none",
    cursor: "pointer",
    marginLeft: "4px",
    ":hover": {
      backgroundColor: "#b52a2d",
    },
  },
  // Main content area
  body: {
    backgroundColor: "#1b1a2e",
    backgroundImage: "radial-gradient(ellipse at center, #2d2b4a 0%, #1b1a2e 70%)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    paddingTop: "32px",
    paddingBottom: "32px",
    paddingLeft: "24px",
    paddingRight: "24px",
    gap: "12px",
  },
  avatarRing: {
    width: "88px",
    height: "88px",
    borderRadius: "50%",
    border: "3px solid #7b83eb",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#3b3a5a",
  },
  avatarIcon: {
    color: "#a8a5d0",
    fontSize: "36px",
  },
  callerName: {
    fontSize: "18px",
    fontWeight: 600,
    color: "#fff",
    textAlign: "center",
  },
  callerPhone: {
    fontSize: "13px",
    color: "#b0aec8",
    textAlign: "center",
  },
});
