import { makeStyles, tokens } from "@fluentui/react-components";

export const useAddPatientFormStyles = makeStyles({
  overlay: {
    position: "fixed",
    top: 0,
    left: 0,
    width: "100vw",
    height: "100vh",
    backgroundColor: "rgba(0, 0, 0, 0.4)",
    zIndex: 10000,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  modal: {
    backgroundColor: tokens.colorNeutralBackground1,
    borderRadius: "8px",
    width: "720px",
    maxHeight: "85vh",
    display: "flex",
    flexDirection: "column",
    boxShadow: "0 8px 32px rgba(0, 0, 0, 0.24)",
    overflow: "hidden",
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: "16px",
    paddingBottom: "16px",
    paddingLeft: "24px",
    paddingRight: "12px",
    borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
  },
  headerTitle: {
    fontSize: tokens.fontSizeBase500,
    fontWeight: tokens.fontWeightSemibold,
    color: tokens.colorNeutralForeground1,
  },
  body: {
    flex: 1,
    overflowY: "auto",
    paddingTop: "20px",
    paddingBottom: "20px",
    paddingLeft: "24px",
    paddingRight: "24px",
    display: "flex",
    flexDirection: "column",
    gap: "24px",
  },
  sectionTitle: {
    fontSize: tokens.fontSizeBase300,
    fontWeight: tokens.fontWeightSemibold,
    color: tokens.colorNeutralForeground1,
    marginBottom: "12px",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  sectionIcon: {
    color: tokens.colorNeutralForeground3,
  },
  fieldGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "16px",
  },
  fieldFullWidth: {
    gridColumn: "1 / -1",
  },
  addressRow: {
    display: "grid",
    gridTemplateColumns: "2fr 1fr 1fr",
    gap: "16px",
    gridColumn: "1 / -1",
  },
  medicationRow: {
    display: "grid",
    gridTemplateColumns: "2fr 1fr 1fr",
    gap: "12px",
    alignItems: "end",
  },
  medicationRowWithAction: {
    display: "grid",
    gridTemplateColumns: "2fr 1fr 1fr auto",
    gap: "12px",
    alignItems: "end",
  },
  medicationList: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  addMedButton: {
    alignSelf: "flex-start",
    marginTop: "4px",
  },
  footer: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "8px",
    paddingTop: "16px",
    paddingBottom: "16px",
    paddingLeft: "24px",
    paddingRight: "24px",
    borderTop: `1px solid ${tokens.colorNeutralStroke2}`,
  },
  removeBtn: {
    minWidth: "auto",
    color: tokens.colorNeutralForeground3,
  },
  campaignDescription: {
    fontSize: "12px",
    color: tokens.colorNeutralForeground3,
    backgroundColor: tokens.colorNeutralBackground2,
    paddingTop: "10px",
    paddingBottom: "10px",
    paddingLeft: "14px",
    paddingRight: "14px",
    borderRadius: "6px",
    lineHeight: "18px",
  },
  outcomesGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    rowGap: "4px",
    columnGap: "24px",
  },
  outcomeItem: {
    fontSize: "12px",
    color: tokens.colorNeutralForeground2,
  },
  campaignSettingsCard: {
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    borderRadius: "8px",
    paddingTop: "16px",
    paddingBottom: "16px",
    paddingLeft: "16px",
    paddingRight: "16px",
  },
  inlineRow: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  inlineRowWrap: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    flexWrap: "wrap",
  },
  inlineLabel: {
    fontSize: "13px",
  },
  outcomesLabel: {
    marginBottom: "4px",
  },
  voicemailCheckbox: {
    marginTop: "8px",
  },
  scheduleButton: {
    height: "44px",
    fontSize: "14px",
    fontWeight: tokens.fontWeightSemibold,
  },
});
