/**
 * OrdersComponent Styles
 *
 * Fluent UI makeStyles definitions for OrdersComponent.
 */

import { makeStyles, tokens } from "@fluentui/react-components";

export const useStyles = makeStyles({
  ordersCard: {
    backgroundColor: "rgba(255,255,255,0.94)",
    borderRadius: "var(--border-radius-xlarge)",
    boxShadow:
      "0px 2px 4px 0px rgba(0,0,0,0.14), 0px 0px 2px 0px rgba(0,0,0,0.12)",
    padding: "var(--spacing-xxxlarge)",
    display: "flex",
    flexDirection: "column",
    width: "100%",
  },
  accordionHeader: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    width: "100%",
  },
  cardHeader: {
    display: "flex",
    alignItems: "center",
    gap: "var(--gap-xlarge)",
    width: "100%",
  },
  expandButton: {
    backgroundColor: "transparent",
    border: "none",
    borderRadius: "var(--border-radius-medium)",
    padding: "var(--spacing-small-4)",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: "24px",
    minHeight: "24px",
    "&:hover": {
      backgroundColor: tokens.colorNeutralBackground1Hover,
    },
  },
  headerContent: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: "2px",
  },
  eyebrow: {
    display: "flex",
    gap: "var(--gap-medium)",
    fontSize: "10px",
    fontWeight: 400,
    lineHeight: "14px",
    color: tokens.colorNeutralForeground1,
    fontFamily: "'Segoe UI', sans-serif",
  },
  title: {
    fontSize: "16px",
    fontWeight: 600,
    lineHeight: "22px",
    color: tokens.colorNeutralForeground1,
    fontFamily: "'Segoe UI', sans-serif",
    margin: 0,
  },
  menuButton: {
    backgroundColor: "transparent",
    border: "none",
    borderRadius: "var(--border-radius-medium)",
    padding: "var(--spacing-small-4)",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: "var(--button-size-standard)",
    "&:hover": {
      backgroundColor: tokens.colorNeutralBackground1Hover,
    },
  },
  toolbar: {
    display: "flex",
    flexDirection: "column",
    gap: "var(--gap-small)",
    width: "100%",
  },
  toolbarActions: {
    display: "flex",
    alignItems: "center",
    gap: "var(--gap-small)",
    width: "100%",
  },
  leftActions: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    gap: "var(--gap-small)",
  },
  toolbarButton: {
    backgroundColor: "transparent",
    border: "none",
    borderRadius: "var(--border-radius-medium)",
    padding: "var(--spacing-small-4)",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: "24px",
    minHeight: "24px",
    color: tokens.colorNeutralForeground2,
    "&:hover": {
      backgroundColor: tokens.colorNeutralBackground1Hover,
    },
  },
  divider: {
    height: "1px",
    backgroundColor: "var(--palette-gray-e0e0e0)",
    width: "100%",
  },
  ordersContent: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    paddingTop: "10px",
    paddingBottom: "var(--spacing-xlarge)",
    width: "100%",
  },
  structuredPlan: {
    backgroundColor: tokens.colorNeutralBackground1,
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    width: "100%",
  },
  orderItem: {
    display: "flex",
    alignItems: "center",
    gap: "var(--gap-large)",
    width: "100%",
  },
  orderBadge: {
    backgroundColor: tokens.colorNeutralBackground5,
    borderRadius: "var(--border-radius-circular)",
    minWidth: "20px",
    height: "20px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "0 4px",
    flexShrink: 0,
  },
  orderBadgeText: {
    fontSize: "10px",
    fontWeight: 600,
    lineHeight: "14px",
    color: tokens.colorNeutralForeground1,
    fontFamily: "'Segoe UI', sans-serif",
  },
  orderTextContainer: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    position: "relative",
    borderRadius: "var(--border-radius-medium)",
    overflow: "hidden",
  },
  orderText: {
    fontSize: tokens.fontSizeBase300,
    fontWeight: 400,
    lineHeight: "20px",
    color: tokens.colorNeutralForeground1,
    fontFamily: "'Segoe UI', sans-serif",
    padding: "6px 10px",
    backgroundColor: "transparent",
    border: "1px solid transparent",
    borderRadius: "var(--border-radius-medium)",
    outline: "none",
    width: "100%",
    boxSizing: "border-box",
  },
  orderFocusIndicator: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: "2px",
    backgroundColor: tokens.colorCompoundBrandStroke,
    borderBottomLeftRadius: "4px",
    borderBottomRightRadius: "4px",
  },
  codeButton: {
    display: "flex",
    alignItems: "center",
    gap: "var(--gap-medium)",
    backgroundColor: "transparent",
    border: "none",
    borderRadius: "var(--border-radius-medium)",
    padding: "6px 12px",
    cursor: "pointer",
    color: tokens.colorNeutralForeground2,
    flexShrink: 0,
    "&:hover": {
      backgroundColor: tokens.colorNeutralBackground1Hover,
    },
  },
  codeIcon: {
    width: "20px",
    height: "20px",
  },
  codeText: {
    fontSize: tokens.fontSizeBase300,
    fontWeight: 600,
    lineHeight: "20px",
    fontFamily: "'Segoe UI', sans-serif",
    color: tokens.colorNeutralForeground2,
  },
  deleteButton: {
    backgroundColor: "transparent",
    border: "none",
    borderRadius: "var(--border-radius-medium)",
    padding: "var(--spacing-medium)",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: tokens.colorNeutralForeground2,
    flexShrink: 0,
    "&:hover": {
      backgroundColor: tokens.colorNeutralBackground1Hover,
    },
  },
  addOrderButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "var(--gap-medium)",
    backgroundColor: "transparent",
    border: "none",
    borderRadius: "var(--border-radius-medium)",
    padding: "6px 12px",
    cursor: "pointer",
    color: tokens.colorNeutralForeground2,
    width: "100%",
    "&:hover": {
      backgroundColor: tokens.colorNeutralBackground1Hover,
    },
  },
  addOrderText: {
    fontSize: tokens.fontSizeBase300,
    fontWeight: 600,
    lineHeight: "20px",
    fontFamily: "'Segoe UI', sans-serif",
  },
  // Dialog styles
  dialogSurface: {
    borderRadius: "var(--border-radius-xlarge)",
    padding: "var(--spacing-huge)",
    maxWidth: "320px",
  },
  dialogHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginBottom: "var(--spacing-xxlarge)",
  },
  dialogTitle: {
    fontSize: tokens.fontSizeBase500,
    fontWeight: 600,
    lineHeight: "28px",
    color: tokens.colorNeutralForeground1,
    fontFamily: "'Segoe UI', sans-serif",
    margin: 0,
  },
  dialogCloseButton: {
    backgroundColor: "transparent",
    border: "none",
    borderRadius: "var(--border-radius-medium)",
    padding: "var(--spacing-small-4)",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: tokens.colorNeutralForeground2,
    marginTop: "-4px",
    marginRight: "-4px",
    "&:hover": {
      backgroundColor: tokens.colorNeutralBackground1Hover,
    },
  },
  dialogContent: {
    fontSize: tokens.fontSizeBase300,
    fontWeight: 400,
    lineHeight: "20px",
    color: tokens.colorNeutralForeground1,
    fontFamily: "'Segoe UI', sans-serif",
    marginBottom: "var(--spacing-huge)",
  },
  dialogActions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "var(--gap-large)",
  },
});

export type OrdersStyles = ReturnType<typeof useStyles>;
